name: weather
description: A new Flutter project.



publish_to: 'none' 











version: 1.1.0+2

environment:
  sdk: ">=2.16.2 <3.0.0"







dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.2.0
  http: ^0.13.4
  provider: ^6.0.2
  bottom_navy_bar: ^6.0.0
 
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.3.5
  url_launcher: ^6.1.5
  path_provider: ^2.0.11
  share_plus: ^4.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0

flutter_icons:
  android: true
  image_path: "assets/appicon/weather.png"

  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:

  
  
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/appicon/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
